# Automatically generated by Pynguin.
import calcul as module_0


def test_case_0():
    try:
        float_0 = None
        calculatrice_0 = module_0.Calculatrice(float_0, float_0)
        assert calculatrice_0.variable_1 is None
        assert calculatrice_0.variable_2 is None
        var_0 = calculatrice_0.division()
    except BaseException:
        print("Valeur invalide")
