# Automatically generated by Pynguin.
import pytest
import calcul as module_0


def test_case_0():
    float_0 = 3272.4041
    calculatrice_0 = module_0.Calculatrice(float_0, float_0)
    assert calculatrice_0.variable_1 == pytest.approx(3272.4041, abs=0.01,
        rel=0.01)
    assert calculatrice_0.variable_2 == pytest.approx(3272.4041, abs=0.01,
        rel=0.01)
    var_0 = calculatrice_0.multiplication()
    assert var_0 == pytest.approx(10708628.593696812, abs=0.01, rel=0.01)


def test_case_1():
    float_0 = -3349.11
    calculatrice_0 = module_0.Calculatrice(float_0, float_0)
    assert calculatrice_0.variable_1 == pytest.approx(-3349.11, abs=0.01,
        rel=0.01)
    assert calculatrice_0.variable_2 == pytest.approx(-3349.11, abs=0.01,
        rel=0.01)
    var_0 = calculatrice_0.addition()
    assert var_0 == pytest.approx(-6698.22, abs=0.01, rel=0.01)
    var_1 = calculatrice_0.soustraction()
    assert var_1 == pytest.approx(0.0, abs=0.01, rel=0.01)
    var_2 = calculatrice_0.division()
    assert var_2 == pytest.approx(1.0, abs=0.01, rel=0.01)
    var_3 = calculatrice_0.addition()
    assert var_3 == pytest.approx(-6698.22, abs=0.01, rel=0.01)
    var_4 = calculatrice_0.soustraction()
    assert var_4 == pytest.approx(0.0, abs=0.01, rel=0.01)
    var_5 = calculatrice_0.addition()
    assert var_5 == pytest.approx(-6698.22, abs=0.01, rel=0.01)


def test_case_2():
    float_0 = 578.909
    calculatrice_0 = module_0.Calculatrice(float_0, float_0)
    assert calculatrice_0.variable_1 == pytest.approx(578.909, abs=0.01,
        rel=0.01)
    assert calculatrice_0.variable_2 == pytest.approx(578.909, abs=0.01,
        rel=0.01)
    var_0 = calculatrice_0.soustraction()
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    float_1 = None
    calculatrice_1 = module_0.Calculatrice(float_1, float_1)
    assert calculatrice_1.variable_1 is None
    assert calculatrice_1.variable_2 is None
